### PR TITLE
Update Buildings.json

### PR DESCRIPTION
**Pull request by SchoeniosX**
Some Acropolis changes

### CODE REVIEW

**Comment by EmperorPinguin** [comment]
The Acropolis is already quite strong I think. If you build 6 acropolises, you can permanently ally all the city states with just a pledge to protect and the Patronage policy.

**Comment by SchoeniosX** [comment]
Hello Emperor Pinguin,

Then I would change the Acropolis again. When im ready, can you give me
your consent? And put the pull request together? You will find out at the
latest.

Sincerely Laurin S.

EmperorPinguin ***@***.***> schrieb am Do., 27. Juni 2024,
21:44:

**Comment by EmperorPinguin** [comment]
I'm open to changing the unique components in this mod, it's in time of an update anyways I think. They must however not make the civs too much stronger, as the unique components are considered to be quite imbalanced already by some.

**Comment by SchoeniosX** [comment]
Hello Emperor Pinguin

I agree. I understand you intentions and will therefore adapt.

Sincerely Laurin S.

EmperorPinguin ***@***.***> schrieb am Fr., 28. Juni 2024,
10:34:

**Comment by SchoeniosX** [comment]
I couldn't get the line in Faith in the Acropolis right. I don't know if this is a disturbing factor, if so could you change it?

**Comment by SchoeniosX** [comment]
Sorry. I don't know how to add correctly icons.

**Comment by SchoeniosX** [comment]
Hello Emperor Pinguin,

I put some pull request in your Mod also in "Unquies From Chubz".   When
you have the time you can  have a look over it?

Laurin Schönwälder ***@***.***> schrieb am Fr., 28. Juni
2024, 12:51:

**Comment by EmperorPinguin** [comment]
Wow, you added a lot of changes, I'll look into it tomorrow!

**Comment by SchoeniosX** [comment]
Hello Emperor Pinguin,

yes some more content. For the Acropolis please view this pull Request. The other pull request (#52) please for the building.jsons. I don't know how to add new icons. However, I wish you a nice day!

**Comment by EmperorPinguin** [comment]
Hello Laurin,

This mod (3rd an 4th Unique Component) is meant to add additional unique buildings and unique units to the nations in the game,  not adding them to all nations in the game, as is the case with th Steel Mill, the Sewer etc. you've been adding. I recommend you make your own mod for this, you can do this easily by copying, pasting and renaming the folder of this mod in the mod directory of Unciv on your PC, and then deleting/changing all the files until you get how you want it. You can then also past your own icons into Image > buildingIcons (don't forget to delete game.atlas and the game.pgn files before loading up Unciv to test if it works).

For the Acropolis, I agree it needs a bit of change, what do you think of this:
increase cost 65 ->75
add Artist slot
remove +1 gold for researching flight

**Pull request closed without merging**
